### ISSUE TITLE
TrimMasks.jsx explodes compound paths

### ISSUE THREAD

**Issue by Dekkerb** [creold/illustrator-scripts#11]
Really great script, have used many times. My issue: TrimMasks unfortunately removes most existing compound paths / groups. 

(Sorry for Dutch interface in screenshots)

If this is unsolvable, a script that can group (or compound) items based on color would help. The workflow would then become: 1) select all countries 2) give each country a unique color 3) run TrimMask 4) Run script GroupbyColor or CompoundByColor.

Keep up the great scripts!!

![image](https://user-images.githubusercontent.com/7647357/233076769-83c680fc-6534-49a8-9f6f-0e2c0c6bb377.png)
![image](https://user-images.githubusercontent.com/7647357/233076861-f305bc25-6034-436b-b08f-2b97d525f325.png)

**Comment by creold** [comment]
@Dekkerb the point is that the Pathfinder panel action releases compound paths. That's why you see this in TrimMasks. 

As for combining colors, I have an [unpublished script](https://gist.github.com/creold/639a993cd31427d4f1ab104deba00c3a) that does this. But it merges colors from all layers in the document, so I recommend copying only the objects you want to merge by color into an empty document.
![UniteByColor](https://user-images.githubusercontent.com/32217031/233762589-9905f747-ff53-43f4-97a9-9ba08fa87bfb.gif)

**Comment by Dekkerb** [comment]
Wow, that is a great script! Would it be difficult to have the same script but instead of uniting, it would use the "exclude" function of pathfinder on the similar colored items? Those two scripts used one after another would completely solve the issue.

**Comment by creold** [comment]
@Dekkerb https://gist.github.com/creold/78122b9867525b9813c353d861ce1c62
